# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08893bd9fd2f6d9f00850d69a88faf4b4fcbf07bc1790368ea660f9bc088c04a68311cfa839d2e52508436a47fbc2aadd8d73082faff011c6a1798b30e6c69f1

test:
  secret_key_base: 94c8f911cbaac7d022b475d83e17060cfb33cb878298a4a1d2f6cc3db9258aece93d80ab96555ca593088d48926bc74ff57d510fd0917c9d25f5c0629ba48590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
