Entry.create!(name: "Mouse")
Entry.create!(name: "RKelley")
Entry.create!(name: "Snoop")
Entry.create!(name: "Eazy")
Entry.create!(name: "Dre")
Entry.create!(name: "Redman")
Entry.create!(name: "Eminem")